### PR TITLE
patch: change colors to be a bit easier on the eye

### PR DESCRIPTION
**Pull request by tq-bit**
Hello guys, 

I've made a few quick tweaks. Will take a closer look next weekend for details. 
Given you like the current changes, I'd happily open another pull request for those, too.

Best regards, 
Tobi

### CODE REVIEW

**Comment by contrasting** [comment]
Sorry @tq-bit I didn't see that you'd opened a PR. I like your colours.

**Review by contrasting — CHANGES_REQUESTED** [review]
Can you undo your edits to the README please

**Comment by tq-bit** [comment]
hey @contrasting 

thanks for your reply.

I've reverted the changes to the readme. 
There's a small conflict with the colors which I cannot resolve myself, please have a look when you're free.

**Comment by contrasting** [comment]
thank you @tq-bit , merged

**Pull request merged**
